# Spring Properties
spring:
  application:
     name: eureka-discovery

# HTTP Server
server:
  port: ${EUREKA_PORT:8761} #cs-ccr-ln4:8958/eureka/

# Eureka Discovery Server
eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 1 # DO NOT DO THIS IN PRODUCTION
    leaseExpirationDurationInSeconds: 2 # DO NOT DO THIS IN PRODUCTION
    preferIpAddress: true
    #metadataMap:
      #The syntax ${x:${y}} is Spring property shorthand for ${x} != null ? ${x} : ${y}
      #instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}} 
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false